### ISSUE TITLE
Update the design and button ui of app

### ISSUE THREAD

**Issue by vaibhavpatl** [vaibhavpatl/Simple-calculator#1]

**Comment by DK-Khambhadiya** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by harikanani** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by vaibhavpatl** [comment]
You are good to go ⚡

**Comment by akashdnb** [comment]
Hey I would like to update UI of this app

**Comment by harikanani** [comment]
@vaibhavpatl Can you please review my PR??

**Comment by akashdnb** [comment]
@harikanani I think your recent PR has too many bugs
It does not even compile.
